version: "3.8"

services:
  worker-api:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - redis

  worker-celery:
    build: .
    command: celery -A app.tasks.pipeline.celery_app worker --loglevel=info --concurrency=4
    env_file:
      - .env
    depends_on:
      - redis

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
